version: '3.8'

services:
  test-backend:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/backend
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - test-db
  test-db:
    image: postgres:15.3
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres-test-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

volumes:
  postgres-test-data:
